from __future__ import annotations

import asyncio
import json
import logging
from datetime import UTC, datetime

logger = logging.getLogger(__name__)

SYNTHETIC_FILES: dict[str, dict[str, str]] = {
    "finance-srv": {
        "files/payroll.xlsx": (
            "employee_id,name,department,gross_monthly\n"
            "F-1001,June Whitfield,Finance,4820.00\n"
            "F-1002,Marcus Delaney,Finance,5310.00\n"
            "F-1003,Priya Raman,Accounting,4675.00\n"
            "# SYNTHETIC LAB DATA - NOT REAL PAYROLL\n"
        ),
        "files/invoices/2026-Q1.txt": (
            "INV-0042 Northwind Traders 18250.00 PAID\n"
            "INV-0043 Umbrella Supplies 9420.00 PENDING\n"
            "INV-0044 Initech Services 31000.00 PAID\n"
            "# SYNTHETIC LAB DATA\n"
        ),
        "files/quarterly_report.pdf": (
            "Quarterly report placeholder - generated by HoneyMesh decoy.\n"
            "Revenue trend: synthetic. Margin trend: synthetic.\n"
        ),
    },
    "hr-srv": {
        "files/employees.csv": (
            "id,name,role,office,started\n"
            "E-201,Alicia Gomez,HR Generalist,Building C,2023-04-11\n"
            "E-202,Tomas Nowak,Recruiter,Building C,2024-09-02\n"
            "E-203,Renée Duval,HR Analytics,Building A,2022-01-17\n"
            "# SYNTHETIC LAB DATA - FABRICATED PEOPLE\n"
        ),
        "files/leave_policy.pdf": (
            "Leave policy: 25 days annual, 10 days sick. "
            "Placeholder generated by HoneyMesh decoy.\n"
        ),
        "files/hiring_plan.xlsx": (
            "role,headcount,budget\nBackend Engineer,3,240000\nSOC Analyst,2,150000\n"
            "# SYNTHETIC LAB DATA\n"
        ),
    },
    "backup-srv": {
        "files/backup-manifest.txt": (
            "2026-10-05T02:00:00Z full/incrypt-ok size=4821930241\n"
            "2026-10-06T02:00:00Z incr size=118234001\n"
            "target: smb://backup-srv/archive\n"
            "# SYNTHETIC LAB DATA\n"
        ),
        "files/infrastructure.txt": (
            "honeygate   10.20.0.2  gateway\n"
            "honeyssh    10.20.0.10 ssh\n"
            "honeyweb    10.20.0.11 web\n"
            "finance-srv 10.20.0.21 finance\n"
            "hr-srv      10.20.0.22 hr\n"
            "# SYNTHETIC LAB TOPOLOGY\n"
        ),
        "files/service-status.txt": (
            "backup-agent   RUNNING\narchive-verifier RUNNING\nretention-job   SCHEDULED\n"
            "# SYNTHETIC LAB DATA\n"
        ),
    },
}


def _html(title: str, body: str) -> str:
    return (
        '<!DOCTYPE html><html><head><meta charset="utf-8">'
        f"<title>{title}</title></head><body>{body}</body></html>"
    )


class DecoyHost:
    """Minimal in-process HTTP decoy host with allowlisted synthetic content only."""

    def __init__(self, name: str, port: int, host: str = "127.0.0.1") -> None:
        self.name = name
        self.port = port
        self.host = host
        self._server: asyncio.Server | None = None
        self._files = SYNTHETIC_FILES.get(name, {})

    @property
    def running(self) -> bool:
        return self._server is not None

    async def start(self) -> None:
        if self._server is not None:
            return
        self._server = await asyncio.start_server(self._handle, self.host, self.port)

    async def stop(self) -> None:
        if self._server is None:
            return
        self._server.close()
        await self._server.wait_closed()
        self._server = None

    async def _handle(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
        try:
            request_line = await asyncio.wait_for(reader.readline(), timeout=5)
            parts = request_line.decode(errors="replace").split()
            while True:
                line = await asyncio.wait_for(reader.readline(), timeout=5)
                if line in (b"\r\n", b"\n", b""):
                    break
            method = parts[0] if parts else "GET"
            path = parts[1] if len(parts) > 1 else "/"
            status, content_type, payload = self._route(method, path)
            self._write_response(writer, status, content_type, payload)
        except (TimeoutError, ConnectionError):
            pass
        finally:
            try:
                writer.close()
                await writer.wait_closed()
            except Exception:
                pass

    def _route(self, method: str, path: str) -> tuple[int, str, str]:
        if method not in {"GET", "HEAD"}:
            return 405, "text/plain", "method not allowed\n"
        clean = path.split("?")[0].rstrip("/") or "/"
        if clean == "/":
            listing = (
                "".join(f"<li>{key}</li>" for key in sorted(self._files)) or "<li>no files</li>"
            )
            body = _html(
                f"{self.name}",
                f"<h1>{self.name}</h1><p>Synthetic decoy host (HoneyMesh lab).</p>"
                f"<ul>{listing}</ul>",
            )
            return 200, "text/html; charset=utf-8", body
        if clean == "/health":
            return 200, "application/json", json.dumps({"service": self.name, "status": "up"})
        if clean == "/files":
            return 200, "application/json", json.dumps({"files": sorted(self._files)})
        if clean.startswith("/files/"):
            key = clean[len("/files/") :]
            content = self._files.get(key)
            if content is None:
                return 404, "text/plain", "not found\n"
            return 200, "text/plain; charset=utf-8", content
        return 404, "text/plain", "not found\n"

    @staticmethod
    def _write_response(
        writer: asyncio.StreamWriter, status: int, content_type: str, payload: str
    ) -> None:
        reason = {200: "OK", 404: "Not Found", 405: "Method Not Allowed"}.get(status, "OK")
        body = payload.encode()
        head = (
            f"HTTP/1.1 {status} {reason}\r\n"
            f"Content-Type: {content_type}\r\n"
            f"Content-Length: {len(body)}\r\n"
            "Server: HoneyMesh-Decoy\r\n"
            "Connection: close\r\n"
            "\r\n"
        ).encode()
        writer.write(head + body)


async def build_local_hosts(
    specs: dict[str, tuple[int, str]], host: str = "127.0.0.1"
) -> dict[str, DecoyHost]:
    """Create (but do not start) decoy hosts for the given name -> (port, type) map."""
    return {name: DecoyHost(name, port, host=host) for name, (port, _) in specs.items()}


def decoy_timestamp() -> str:
    return datetime.now(UTC).isoformat()
